const fs = require('fs');
const path = require('path');

// Path to the cards directory
const cardsDir = path.join(__dirname, 'public/assets/images/data-war/cards');

try {
  // Read directory contents
  const files = fs.readdirSync(cardsDir);

  // Count all files (excluding directories)
  const fileCount = files.filter(file => {
    const filePath = path.join(cardsDir, file);
    return fs.statSync(filePath).isFile();
  }).length;

  // Output path for the generated constant
  const outputPath = path.join(__dirname, 'src/utils/easter-egg.ts');

  // Generate the TypeScript constant file
  const content = `// Auto-generated - do not edit manually
// This file is generated by apps/web/count-images.js
export const CARDS_COUNT = ${fileCount};
`;

  // Write the file
  fs.writeFileSync(outputPath, content);

  console.log(`✓ Generated easter-egg.ts: ${fileCount} cards found`);
} catch (error) {
  console.error('Error generating CARDS_COUNT constant:', error.message);
  process.exit(1);
}
